### ISSUE TITLE
[Question] Is it necessary for Akkoma?

### ISSUE THREAD

**Issue by paulo-roger** [nanos/FediFetcher#118]
Is FediFetcher needed for Akkoma? Are the problems it solves more of a Mastodon thing or is it tied to all platforms of the fediverse?

**Comment by nanos** [comment]
I'm not really sure, to be honest, as I have never used Akkoma.

However, some has set used FediFetcher for Pleroma in the past, so I assume it was needed there. And since Akkoma and Pleroma are very similar, I assume that Akkoma would also benefit from FediFetcher. As far as I know it should work with Pleroma / Akkoma, as long as you leave the `reply-interval-in-hours` option disabled (which it is by default), but again: I have never used Akkoma, so don't know for sure.

Would be happy to get some feedback though, if you manage to get it working

**Comment by nanos** [comment]
Closing this as stale now. Feel free to reopen if needed.
