### ISSUE TITLE
Allow instances to specify a rate-limit

### ISSUE THREAD

**Issue by bentasker** [nanos/FediFetcher#160]
It looks like you've put a lot of work into implementing rate-limiting (e.g. https://github.com/nanos/FediFetcher/pull/124/files and FediFetcher) supports [back-off on HTTP 429](https://github.com/nanos/FediFetcher/blob/main/find_posts.py#L1148).

However, back-off relies on you getting to the point of experiencing a rate-limiting event, which might result in instance admins seeing periodic spikes of heavy load.

Although it's not part of the `robots.txt` spec draft, the `crawl-delay` directive is quite widely adopted, so you could support something like:

```text
User-Agent: FediFetcher
Allow: /
crawl-delay: 5
```

The directive is also supported by `robotparser` (so you'd access the value with `robotParser.can_fetch(user_agent)` it'll return `None` if it hasn't been set).

This would allow admins to minimise the likelihood of load spikes by specifying a maximum crawl-rate (with the effect that you might then never actually encounter a `HTTP 429`). 

Although it would complicate the logic, on the script side, you could potentially optimise execution by maintaining per-domain queues of things to fetch, so whilst you're in a `crawl-delay` backoff for one domain you can still be fetching from others.

**Comment by nanos** [comment]
Thanks. I did actually think about it at the time, but decided against it, because I fear it might cause confusion for the remote instance’s owner. 

This is because FediFetcher doesn’t work like most bots. 

Eg if someone put a crawl-delay of 5 for Google bit, then you’d expect Google bot to only recrawl after 5 sec. 

But there isn’t a single FediFetcher. So if you do crawl-delay of 5 for FediFetcher, then if 20 instances of FediFetcher access this endpoint, there’ll be 20 requests, then a 5 sec pause, then 20 more requests etc. 

I fear this might lead to operators thinking FediFetcher doesn’t honour robots.txt and cause more problems than it solves. 

Hence I’m inclined not to implement this.

**Comment by bentasker** [comment]
That seems fair, though it's probably less likely to be confusing now that you've included instance names in user-agents.
