### ISSUE TITLE
[request] fetch new posts with recently followed tags from remote instances

### ISSUE THREAD

**Issue by kevanloy** [nanos/FediFetcher#40]
Running a single user instance, I still don't see a lot of posts for hashtags—established and popular ones like #DogsOfMastodon and current events are useless. 

I would like to add a fetch recently followed tag posts, perhaps from a specified remote instance (e.g. mastodon.social). 

The [tags docs](https://docs.joinmastodon.org/methods/followed_tags/#get) don't look like there's a great way to see the concept of "newly followed tags" other than, perhaps, a tag's ID. 

The established parameters of number of posts, timeframe et cetera would be useful here as well. 

In a way this is a bit like a relay I suppose, but much more specific.

**Comment by nanos** [comment]
Thanks for that report. 

Unfortunately FediFetcher is the wrong tool for that job. 

However, there are two great tools available for the job:

https://github.com/g3rv4/GetMoarFediverse together with FakeRelay is an app you run (either as an application on your server, or as GitHub action). You tell it which hashtags you are interested in, and which servers it should fetch those hashtags from, and it just goes ahead and does it (the advantage of running it from your local server is that it can fetch hashtags you follow from the api, so after initial configuration, it just works by always fetching all your followed hashtags)

https://relay.fedi.buzz is basically the same, but running as a service without the ability to configure servers. As such some hashtags are incredibly noisy on there, as they pull in hashtags from a very large number of servers. 

Those services (I use them both on my instance) work great together with FediFetcher:

they’ll fetch the tagged posts, and FediFetcher will fetch the replies, which you would otherwise be missing.
