### ISSUE TITLE
Enhancement: add the ability to parse messages from Peertube, Kbin, and Lemmy

### ISSUE THREAD

**Issue by csolisr** [nanos/FediFetcher#55]
Currently, if an user is following an account on a service that is not a microblog (such as Peertube, Kbin, or Lemmy) the backfill requests fails, typically with the error message "Error parsing toot URL". Checking on the source code, it seems like the application is hardcoded to support only URLs from Mastodon, Pleroma, and PixelFed. What is required to parse URLs from the other services listed above?

**Comment by nanos** [comment]
Thanks for your interest in this. I’d love to see FediFetcher extended for other servers/protocols, so this is something Od very gladly see any PRs for. 

The following is needed, in order to make this possible:

Firstly you need to figure out if peertube, kbin, and lemmy actually support the Mastodon context api? Any server that doesn’t, is impossible to support without major rewrite. (I did look into doing this via the ActivityPub API, but support for that is amazingly even sketchier than for the mastodon api). I’d be open to this, but it would introduce extra complexity. 

For any server that supports the mastodon api, it’s really easy to implement:

1) write a case for extracting status ID from status url in the `parse_url` function: 

https://github.com/nanos/FediFetcher/blob/535bf1f40435a58d4581977da9c9056113646d47/find_posts.py#L446

2) write a case for extracting profile ID from profile URL in the `parse_user_url` function here:

https://github.com/nanos/FediFetcher/blob/535bf1f40435a58d4581977da9c9056113646d47/find_posts.py#L429

that would be it.

**Comment by nanos** [comment]
I'm really really please to see @Teqed is currently working on a PR to implement Lemmy support for both backfilling profiles and fetching context in #56 

Also serves as a good template on how to import posts from software that doesn't support the Mastodon API!

**Comment by nanos** [comment]
With Lemmy implemented, I’ve split this out into two separate issues: #73 and #74
