### ISSUE TITLE
Enhancement: Add CalcKey Instance Support

### ISSUE THREAD

**Issue by MrHamel** [nanos/FediFetcher#60]
CalcKey's API documentation can be found at [https://calckey.social/api-doc](https://calckey.social/api-doc)

For both pulling in posts, but also updating timelines, etc.

**Comment by Teqed** [comment]
Additional information:

Calckey is downstream of Misskey, differences are noted.

- `.well-known/nodeinfo` response: Yes
- Nodeinfo path: `{server}/nodeinfo/2.0` and `{server}/nodeinfo/2.1`
- Nodeinfo response:  `misskey` or `calckey`
- Users URL pattern: `{server}/@{user}`
- "Posts" URL pattern: `{server}/notes/{id}`

Calckey's API documentation mentions [notes/children](https://calckey.social/api-doc#operation/notes/children) and [notes/conversation](https://calckey.social/api-doc#operation/notes/conversation) endpoints which can be POSTed to using a noteID as parsed from the URL. This appears to function similar to Mastodon's [Context API](https://docs.joinmastodon.org/entities/Context/) and respectively fetch ancestors and descendants of a "note".

A CLI example: `curl -X POST -H "Content-type: application/json" -H "Accept: application/json" -d '{ "noteId": "{id}" }' {server}/api/notes/children` will return a JSON with the replies, including a URL that can be handed back to the local Mastodon server's [search API](https://docs.joinmastodon.org/methods/search/) for lookup.

For user profile backfilling, there is a [user/notes](https://calckey.social/api-doc#operation/users/notes) endpoint but it requires a `userID` which **does not** parse from the user's name in the URL. It should be possible to make a request against the [users/search endpoint](https://calckey.social/api-doc#operation/users/search) and provide the parsed username as the `query` parameter, which will return the required `userID`.

Because the user URLs match the same pattern as Mastodon profiles, the choices here would be to either:
1. After failing against any Mastodon API, attempt Misskey/Calckey API.
2. Implement `nodeinfo` as [discussed here](https://github.com/nanos/FediFetcher/pull/56#issuecomment-1615083362) to determine the appropriate API.

**Comment by nanos** [comment]
Thanks for the suggestion @MrHamel and thanks for the detailed report @Teqed !

> For user profile backfilling, there is a [user/notes](https://calckey.social/api-doc#operation/users/notes) endpoint but it requires a userID which does not parse from the user's name in the URL. It should be possible to make a request against the [users/search endpoint](https://calckey.social/api-doc#operation/users/search) and provide the parsed username as the query parameter, which will return the required userID.

That's the same with Mastodon, see https://github.com/nanos/FediFetcher/blob/213ef57abe9c6f6c052306c776739c72a9301f19/find_posts.py#L216 annoyingly a different path, though.

> Because the user URLs match the same pattern as Mastodon profiles, the choices here would be to either:
> 1. After failing against any Mastodon API, attempt Misskey/Calckey API.
> 2 Implement nodeinfo as https://github.com/nanos/FediFetcher/pull/56#issuecomment-1615083362 to determine the appropriate API.

I'm personally strongly in favour of the 2nd option here. Doing 2 requests per user seems wasteful. 

I'm not currently having capacity to actually implement this, but hopefully later in the summer. If you have an itch, and the time, I'd be very happy, too, though 😉

**Comment by MrHamel** [comment]
Let's reopen this issue since the script still does not import posts into CalcKey/FireFish instances, thanks.

**Comment by nanos** [comment]
Apologies @MrHamel. Like @ToadKing i understood this issue to mean to offer support for pulling in content from Calckey/Firefish instances, not to actually support them. 

I need to be honest though: I do not have a Firefish instance, so I’m unable to implement Firefish support myself. Unless someone else came along and implemented this, and was willing to commit to ongoing testing and support Firefish, this is unfortunately very unlikely to be implemented in FediFetcher.
