### ISSUE TITLE
Run cancelled: getAllRepliesToKnownPosts (505bcdd)

### ISSUE THREAD

**Issue by huckabarry** [nanos/FediFetcher#68]
Since running this action yesterday, I’ve received the following email approximately every 7 minutes:

![IMG_4920](https://github.com/nanos/FediFetcher/assets/98623388/bc2a7c38-4553-4bd9-b427-d5da4d38db70)

What does this mean and how do I fix it?

**Comment by Teqed** [comment]
As you may have already noticed, these aren't errored jobs, but skipped schedules because the previous job was still running, and it will wait until the next schedule to try again. GitHub considers cancelled workflows as failed.

The reason you are receiving emails about these cancelled workflows is your GitHub email notification settings.

Slightly below where you cropped the screenshot, select [Manage your GitHub Actions notifications.](https://github.com/settings/notifications)

![image](https://github.com/nanos/FediFetcher/assets/5181964/4b913783-20ea-4032-afea-91839271f7ba)

From here, you can choose how to be notified.

![image](https://github.com/nanos/FediFetcher/assets/5181964/56c41d48-3028-4c1b-8dae-fd2035c5fe23)

For more information about notifications for workflow runs, see GitHub's docs [here.](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs) To see some community discussion about the limitations of the configuration options, [see here.](https://github.com/orgs/community/discussions/18039)

**Comment by nanos** [comment]
Yes, as @Teqed said: This is expected because FediFetcher can run longer than 10 minutes.

I would try and adjust your notification settings. If you cannot do that, you can either reduce the frequency here: https://github.com/huckabarry/FediFetcher/blob/505bcdd048d00161e2d9cca4ecc1dceec6e94d39/.github/workflows/get_context.yml#L7 or create a rule in your mail client to bin these notifications automatically.

Hopefully these should get fewer and fewer, as FediFetcher starts to catch up, as well.

**Comment by huckabarry** [comment]
@Teqed @nanos 

Thank you both!

I may not have to change the settings since the situation seems to have resolved itself with time, as you described. But I'll keep your notes in my back pocket in case I run into it again.
