### ISSUE TITLE
duplicate requests

### ISSUE THREAD

**Issue by 33b5e5** [nanos/FediFetcher#85]
I noticed FediFetcher repeats the same request over and over:

```bash
$ sudo zgrep "GET /api/v1/statuses/110873511959420147/context" /var/log/nginx/access.log* | wc -l
3762
```

and...

```bash
$ sudo zgrep "GET /api/v1/statuses/109860069987097044/context" /var/log/nginx/access.log*  | wc -l
3794
```

There are other examples; these are just two of the noisiest.

The full line of one of these requests is:

```txt
/var/log/nginx/access.log.9.gz:2a01:4f8:c012:25c9::1 - - [29/Sep/2023:23:50:47 -0700] "GET /api/v1/statuses/110873511959420147/context HTTP/1.1" 200 6266 "-" "FediFetcher (https://go.thms.uk/mgr)"
```

All these duplicate requests are coming from `FediFetcher (https://go.thms.uk/mgr)` at 2a01:4f8:c012:25c9::1.

**Comment by nanos** [comment]
Thanks for this @33b5e5 

This is most likely expected behaviour: FediFetcher checks for new replies using the context endpoint every time it's being run. Most people run FediFetcher every 1/5/15 minutes, so it's expected that there'll be lots of requests to that endpoint.

Unfortunately there is no other way to check for new replies within Mastodon 😔
